#!/bin/sh
### BEGIN INIT INFO
# Provides:          vyos-cloudinit
# Required-Start:    vyatta-router
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load user VyOS config or run user script
# Description:       Load user VyOS config or run user script.
### END INIT INFO

. /lib/lsb/init-functions

log_action_begin_msg "Starting vyos-cloudinit"

/usr/local/bin/vyos-cloudinit

log_action_end_msg $?
